import {Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../../Component/Navbar/Navbar";
import Footer from "../../Component/Footer/Footer";
import LetsTalk from "../../Component/Home/LetsTalk";


export const metadata = {
  title: "PURPLEBOT DIGITAL LTD",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], 
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        
      >
        <Navbar />
        {children}
        <LetsTalk /> 
        <Footer />
      </body>
    </html>
  );
}
